In [1]:
import json_tricks
answer = {}


inputs = json_tricks.load(open('inputs/inputs.json', 'r'))

In [2]:
inputs

[OrderedDict([('x', array([ 0.49671415, -0.1382643 ])),
              ('w',
               array([ 0.64768854,  1.52302986, -0.23415337, -0.23413696]))]),
 OrderedDict([('x', array([1.57921282, 0.76743473])),
              ('w',
               array([-0.46947439,  0.54256004, -0.46341769, -0.46572975]))]),
 OrderedDict([('x', array([ 0.24196227, -1.91328024])),
              ('w',
               array([-1.72491783, -0.56228753, -1.01283112,  0.31424733]))]),
 OrderedDict([('x', array([-0.90802408, -1.4123037 ])),
              ('w',
               array([ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819]))]),
 OrderedDict([('x', array([-0.54438272,  0.11092259])),
              ('w',
               array([-1.15099358,  0.37569802, -0.60063869, -0.29169375]))]),
 OrderedDict([('x', array([-0.60170661,  1.85227818])),
              ('w',
               array([-0.01349722, -1.05771093,  0.82254491, -1.22084365]))]),
 OrderedDict([('x', array([ 0.2088636 , -1.95967012])),
              ('

# Backpropagation Practice

You are given a graph of operations:

<img src="imgs/task_2_4_graph_02.png" width="400" height="300" />

# Task 1

Write a function that calculates the value of this graph for any given input vector `x` and set of coefficients $b_1, b_2, c_1, c_2$ packed as vector of weights `w`.
In this function also return all the $z$ values.

In [3]:
import numpy as np

## YOU CAN DEFINE ANY FUNCTIONS YOU NEED ##
## YOUR CODE HERE ##

def sigmoid(t):
    return 1 / (1 + np.exp(-t))

def graph_value(x, w):
    y = x
    ## YOUR CODE HERE ##
    x1, x2 = x[0], x[1]
    b1, b2, c1, c2 = w[0], w[1], w[2], w[3]
    z1 = x1 + b1
    z2 = x2 + b2
    z3 = sigmoid(z1) 
    z4 = sigmoid(z2)
    z5 = np.tanh(z2)
    z6 = c2 * z5
    z7 = z1 * z4
    z8 = c1 * z7
    z9 = z3 * z6
    y = z8 + z9
    z = np.array([z1, z2, z3, z4, z5, z6, z7, z8, z9])
    
    ###end
    return y, z

In [4]:
answer['graph_value'] = [graph_value(**input) for input in inputs]

In [5]:
answer['graph_value']

[(-0.3709437475832409,
  array([ 1.14440269,  1.38476556,  0.75848706,  0.79975528,  0.88201393,
         -0.20651206,  0.91524209, -0.21430702, -0.15663672])),
 (-0.707721843991169,
  array([ 1.10973843,  1.30999477,  0.75208034,  0.78751228,  0.86427409,
         -0.40251816,  0.87393264, -0.40499585, -0.302726  ])),
 (0.059224013700513646,
  array([-1.48295556, -2.47556777,  0.18498141,  0.07758882, -0.98594868,
         -0.30983174, -0.11506077,  0.11653713, -0.05731311])),
 (0.8461752790658715,
  array([ 0.55762469, -1.63808   ,  0.63590276,  0.16272649, -0.92720368,
          1.32103177,  0.09074031,  0.00612753,  0.84004775])),
 (0.6102246564906443,
  array([-1.6953763 ,  0.48662061,  0.15507011,  0.61931001,  0.45153014,
         -0.13170852, -1.04996352,  0.63064871, -0.02042405])),
 (-0.6317028591739816,
  array([-0.61520384,  0.79456726,  0.35087305,  0.68881117,  0.6609886 ,
         -0.80696374, -0.42375927, -0.34856103, -0.28314183])),
 (-0.1608118300518797,
  array([-1.1

# Task 2

In this graph, find all direct derivatives of all the values over $z$ or $x$ or $w$.

For example, if $y = z_8 + z_9$, you need to find only $\partial_{z_9} y$ and $\partial_{z_8} y$ for that operation.

You have to do that for all the intermediate signals.

Write the result in the form of a dictionary, for example, $\partial_{z_9} y$:

```
['dy_dz9'] = 1
```

In [6]:
def graph_derivatives(x, w):
    res = {}
    ## YOUR CODE HERE ##
    res['dy_dz8'] = 1.0
    res['dy_dz9'] = 1.0
    
    
    x1, x2 = x[0], x[1]
    b1, b2, c1, c2 = w[0], w[1], w[2], w[3]
    z1 = x1 + b1
    z2 = x2 + b2
    z3 = sigmoid(z1)
    z4 = sigmoid(z2)
    z5 = np.tanh(z2)
    z6 = c2 * z5
    z7 = z1 * z4
    z8 = c1 * z7
    z9 = z3 * z6
    y = z8 + z9
    
    res['dz9_dz3'] = z6
    res['dz9_dz6'] = z3
    res['dz8_dc1'] = z7
    res['dz8_dz7'] = c1
    res['dz6_dc2'] = z5
    res['dz6_dz5'] = c2
    res['dz7_dz1'] = z4
    res['dz7_dz4'] = z1
    res['dz5_dz2'] = 1.0 - z5**2
    res['dz4_dz2'] = z4 * (1.0 - z4)
    res['dz3_dz1'] = z3 * (1.0 - z3)
    res['dz2_dx2'] = 1.0
    res['dz2_db2'] = 1.0
    res['dz1_dx1'] = 1.0
    res['dz1_db1'] = 1.0
    #end code

    return res

In [7]:
answer['graph_derivatives'] = [graph_derivatives(**input) for input in inputs]

# Task 3

Using the values of the derivatives, calculated above:
- extract a dictionary of values that are needed to calculate $\partial_{c_1} y$
- calculate that derivative

In [8]:
def dy_dc1(x, w):
    selected_derivs = {}
    dy_dc1 = 0

    ## YOUR CODE HERE ##
    y, z = graph_value(x, w)
    z7 = z[6]
    selected_derivs['dy_dz8'] = 1.0
    selected_derivs['dz8_dc1'] = z7
    dy_dc1 = selected_derivs['dy_dz8'] * selected_derivs['dz8_dc1']
    #end

    return selected_derivs, dy_dc1

In [9]:
answer['dy_dc1'] = [dy_dc1(**input) for input in inputs]

# Task 4
Using the values of the derivatives, calculated above:
- extract a dictionary of values that are needed to calculate $\partial_{c_2} y$
- calculate that derivative

In [10]:
def dy_dc2(x, w):
    selected_derivs = {}
    dy_dc2 = 0

    ## YOUR CODE HERE ##
    #y->z9->z6->c2
    y, z = graph_value(x, w)
    z3 = z[2]
    z5 = z[4]
    selected_derivs['dy_dz9'] = 1.0
    selected_derivs['dz9_dz6'] = z3
    selected_derivs['dz6_dc2'] = z5
    dy_dc2 = selected_derivs['dy_dz9'] * selected_derivs['dz9_dz6'] * selected_derivs['dz6_dc2']
    #end

    return selected_derivs, dy_dc2

In [11]:
answer['dy_dc2'] = [dy_dc2(**input) for input in inputs]

# Task 5
Using the values of the derivatives, calculated above:
- extract a dictionary of values that are needed to calculate $\partial_{b_1} y$
- calculate that derivative

In [12]:
def dy_db1(x, w):
    selected_derivs = {}
    dy_db1 = 0

    ## YOUR CODE HERE ##
    y, z = graph_value(x, w)
    z3 = z[2]
    z4 = z[3]
    z6 = z[5]
    b1, b2, c1, c2 = w[0], w[1], w[2], w[3]
    selected_derivs['dy_dz8'] = 1.0
    selected_derivs['dz8_dz7'] = c1
    selected_derivs['dz7_dz1'] = z4
    selected_derivs['dy_dz9'] = 1.0
    selected_derivs['dz9_dz3'] = z6
    selected_derivs['dz3_dz1'] = z3 * (1.0 - z3)  # Derivative of sigmoid(z1)
    selected_derivs['dz1_db1'] = 1.0
    up = selected_derivs['dy_dz8'] * selected_derivs['dz8_dz7'] * selected_derivs['dz7_dz1']
    low = selected_derivs['dy_dz9'] * selected_derivs['dz9_dz3'] * selected_derivs['dz3_dz1']
    dy_db1 = (up + low) * selected_derivs['dz1_db1']
    #end code

    return selected_derivs, dy_db1

In [13]:
answer['dy_db1'] = [dy_db1(**input) for input in inputs]

# Task 6
Using the values of the derivatives, calculated above:
- extract a dictionary of values that are needed to calculate $\partial_{b_2} y$
- calculate that derivative

In [14]:
def dy_db2(x, w):
    selected_derivs = {}
    dy_db2 = 0

    ## YOUR CODE HERE ##
    y, z = graph_value(x, w)
    z1 = z[0]
    z3 = z[2]
    z4 = z[3]
    z5 = z[4]
    b1, b2, c1, c2 = w[0], w[1], w[2], w[3]
    selected_derivs['dy_dz8'] = 1.0
    selected_derivs['dz8_dz7'] = c1
    selected_derivs['dz7_dz4'] = z1
    selected_derivs['dz4_dz2'] = z4 * (1.0 - z4)  # Derivative of sigmoid(z2)
    selected_derivs['dy_dz9'] = 1.0
    selected_derivs['dz9_dz6'] = z3
    selected_derivs['dz6_dz5'] = c2
    selected_derivs['dz5_dz2'] = 1.0 - z5**2      # Derivative of tanh(z2)
    selected_derivs['dz2_db2'] = 1.0
    up = (selected_derivs['dy_dz8'] * 
                  selected_derivs['dz8_dz7'] * 
                  selected_derivs['dz7_dz4'] * 
                  selected_derivs['dz4_dz2'])
    low = (selected_derivs['dy_dz9'] * 
                  selected_derivs['dz9_dz6'] * 
                  selected_derivs['dz6_dz5'] * 
                  selected_derivs['dz5_dz2'])
    
    dy_db2 = (up + low) * selected_derivs['dz2_db2']

    #end code

    return selected_derivs, dy_db2

In [15]:
answer['dy_db2'] = [dy_db2(**input) for input in inputs]

In [16]:
json_tricks.dump(answer, '.answer.json')

'{"graph_value": [[-0.3709437475832409, {"__ndarray__": [1.1444026911119252, 1.3847655552368408, 0.7584870610795774, 0.7997552788670441, 0.8820139250377154, -0.20651205639513331, 0.9152420933664135, -0.21430702485059627, -0.15663672273264462], "dtype": "float64", "shape": [9]}], [-0.707721843991169, {"__ndarray__": [1.1097384295724393, 1.3099947727388734, 0.7520803434104762, 0.7875122811662103, 0.864274090196551, -0.40251815904439764, 0.8739326421703995, -0.4049958487081057, -0.30272599528306326], "dtype": "float64", "shape": [9]}], [0.059224013700513646, {"__ndarray__": [-1.4829555609469987, -2.4755677738987707, 0.1849814142676477, 0.0775888179168375, -0.9859486784088057, -0.3098317422658027, -0.11506076899707829, 0.11653712756985114, -0.0573131138693375], "dtype": "float64", "shape": [9]}], [0.8461752790658715, {"__ndarray__": [0.5576246934003432, -1.6380800018218271, 0.6359027622340152, 0.16272648639125625, -0.9272036833188647, 1.321031766058989, 0.09074030708203938, 0.0061275300300